# Basic Python

## 1. Split this string

In [26]:
s = "Hi there Sam!"

In [27]:
s_list = s.split(" ")
for ele in s_list:
  print(ele)

Hi
there
Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [28]:
planet = "Earth"
diameter = 12742

In [29]:
text = "The diameter of {planetName} is {diameterValue} kilometers.".format(planetName=planet,diameterValue=diameter)
print(text)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [30]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [31]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [32]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [33]:
arr1 = np.zeros(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [34]:
arr2 = np.ones(10)*5
print(arr2)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [35]:
arr3 = np.arange(20,35,2)
print(arr3)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [36]:
arr4 = np.arange(0,9).reshape(3,3)
print(arr4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr5 = np.concatenate((a, b))
print(arr5)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [38]:
import pandas as pd


In [39]:
df = pd.DataFrame(np.random.randint(0,100,size=(3, 2)), columns=list('AB'))
print(df)

    A   B
0  27  50
1  45  16
2  83  42


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [40]:
import pandas as pd 
per1 = pd.date_range(start ='1-1-2023', end ='5-10-2023', freq ='10D')
  
for val in per1:
    print(val)

2023-01-01 00:00:00
2023-01-11 00:00:00
2023-01-21 00:00:00
2023-01-31 00:00:00
2023-02-10 00:00:00
2023-02-20 00:00:00
2023-03-02 00:00:00
2023-03-12 00:00:00
2023-03-22 00:00:00
2023-04-01 00:00:00
2023-04-11 00:00:00
2023-04-21 00:00:00
2023-05-01 00:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [41]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [42]:
import pandas
df = pandas.DataFrame(lists, columns =['SNo.', 'Name', 'Age']) 
print(df)

   SNo. Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
